# Generated by Django 4.2.7 on 2024-03-29 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='users2',
            fields=[
                ('login2', models.TextField()),
                ('password2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.users')),
            ],
        ),
        migrations.CreateModel(
            name='users3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('us', models.ManyToManyField(to='app.users')),
            ],
        ),
    ]
